# mobile/pubspec.yaml
"""
Flutter dependencies for mobile app.
Includes Bloc, SQflite, HTTP, localization.
"""
name: retail_insights
description: Mobile-first retail data insights app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.3
  http: ^1.2.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  fuzzywuzzy: ^0.0.2
  charts_flutter: ^0.12.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/