# .github/workflows/ci-mobile.yml
"""
CI for mobile: Test, build APK/IPA.
Runs on push/PR to mobile files.
"""
name: Mobile CI

on:
  push:
    branches: [main, develop]
    paths: ['mobile/**']
  pull_request:
    paths: ['mobile/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      - name: Install deps
        run: cd mobile && flutter pub get
      - name: Test
        run: cd mobile && flutter test
      - name: Build APK
        run: cd mobile && flutter build apk --release
      - name: Build IPA
        run: cd mobile && flutter build ios --release --no-codesign